<?php echo $this->form; ?>

<?php foreach($this->pictures as $pictures) : ?>
<div class="imagebox">
        <div class="pic"><a href="<?php echo $this->url(array('controller'=>'index','action'=>'viewpicture', 'id'=>$this->escape($pictures->picture_id)));?>"><img alt=""  src="../pictures/thumbs/<?php echo $this->escape($pictures->filename);?>" /></a> </div>
        <!--- turha ? <div class="uploadtime" style="padding: 0px 0px 10px 20px;"><?php echo date('d.m.Y H:i:s', strtotime($this->escape($pictures->uploadtime))); ?></div>--->
</div>
<?php endforeach; ?>

<div class="clear"></div>
<br /><br />
<div id="paging" style="text-align: center; margin: 0px;">Previous - Next</div>
