<?php

$this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1');
$this->headMeta()->appendName('description', 'PicLeaks - the open source picture site');
$this->headMeta()->appendName('author', 'Heikkilä, Erkkilä, Levänen');
$this->headMeta()->appendName('keywords', 'images,humor,nsfw,comics');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');

$this->headTitle()->setSeparator(' :: ');
$this->headTitle('PicLeaks');

$indexLink = $this->url(array('controller' => 'index', 'action' => 'index'), null, true);
$RegisterLink = $this->url(array('controller' => 'index', 'action' => 'register'), null, true);
$UploadLink = $this->url(array('controller' => 'index', 'action' => 'upload'), null, true);
$AdvancedSearchLink = $this->url(array('controller' => 'index', 'action' => 'advanced-search'), null, true);
$FaqLink = $this->url(array('controller' => 'index', 'action' => 'faq'), null, true);

if ($this->doctype()->isHtml5()) echo $this->doctype();

?>
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    
	<?php $this->headLink()->prependStylesheet($this->baseUrl() . '/css/site.css'); ?>
    
    <?php echo $this->headLink(); ?>
    <?php $this->headScript()->prependFile($this->baseUrl() . '/js/libs/modernizr-1.7.min.js'); ?>
</head>

<body class="png_bg">
<div id="container" class="box_round box_shadow box_rgba">
    <div id="header">
    <div id="header_left">
        <img src="/pictures/android_logo.png" alt="Android" width="80" height="80" />
        <a href="<?php echo $indexLink; ?>"><strong style="color:pink; font-size: 72px; text-shadow: 2px 2px 2px #B2878F;">
        PIC</strong><strong style="color:greenyellow; font-size: 72px; text-shadow: 2px 2px 2px #24f118;">LEAKS</strong>
        </a>
        <p class="description">You can leak anything</p>
    </div>
    <div id="header_right">
        <?php echo $this->loggedInAs(); ?>
        <br />
        <?php echo $this->searchBox(); ?>
    </div>
    </div>
    <div id="menu" class="box_text_shadow">
        <a href="<?php echo $RegisterLink ?>">Register</a>
        <a href="<?php echo $UploadLink ?>">Upload</a>
        <a href="<?php echo $AdvancedSearchLink ?>">Advanced Search</a>
        <a href="<?php echo $FaqLink ?>">FAQ</a>
    </div>
    <div id="content" role="main">
        <h1><?php echo $this->escape($this->title); ?></h1>
        <?php echo $this->layout()->content; ?>
    </div>
    <div class='clear'>&nbsp;</div> 
    <div id="footer">
    <p>Pictures in database: <?php echo rand(9000, 9999); ?> | <?php echo rand(0, 999); ?> users online | picleaks@gmail.com</p>
    <p>Sponsored by <a href="http://www.zombo.com"><strong>Zombo Chemicals</strong></a></p>
    </div>
        <!-- jQuery test -->
        <div id="test" style="width='100%'; height='60px'; padding: 10px; display:none;">
            <h2>jQuery is loaded!</h2>
            <p>...you can now safely remove this element.</p>
        </div>
</div>

  <!--[if lt IE 7 ]>
    <script>DD_belatedPNG.fix("img, .png_bg");</script>
  <![endif]-->
    
<?php $this->headScript()->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js'); ?>
<?php //$this->headScript()->appendFile($this->baseUrl() . '/js/plugins.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl() . '/js/script.js'); ?>
<?php echo $this->headScript(); ?>
</body>
</html>